name: Build Workflow
on:
  push:
#    branches: master
jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Get Build Version
        run: |
            $buildversion = "1.0."+$Env:GITHUB_RUN_NUMBER
            echo "Build Number: $buildversion"
            echo "version=$buildversion" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10.11'
          architecture: 'x64'

      - name: Install GKFlasher Requirements
        run: |
          pip install -r requirements.txt
          
      - name: Install Build Environment Prerequisites
        run: |
          pip install pyinstaller==6.12.0
          pip install cryptography==43.0.3
          pip install pillow==11.0.0
          
      - name: Build EXE Package
        run: |
          python -m PyInstaller .github/workflows/gui.spec
#  for debug purposes, upload the build artifact as a zip.         
      - uses: actions/upload-artifact@v4
        with:
          ##name: Upload PyInstaller "Output" Directory
          path: dist/*

      - name: Install WiX
        run: dotnet tool install --global wix --version 5.0.2

      - name: Build MSI Package
        run: |
           candle .github/workflows/dialog.wxs .github/workflows/ui.wxs .github/workflows/product.wxs -dversion="${{env.version}}"
           light -ext WixUIExtension -ext WixUtilExtension -sacl -spdb  -out ./GKFlasher-${{env.version}}-amd64.msi ./dialog.wixobj ./ui.wixobj ./product.wixobj

      - name: Upload MSI to Releases
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{env.version}}
          prerelease: false
          title: ${{env.version}}
          files: |
            GKFlasher-${{env.version}}-amd64.msi
