name: Build Workflow
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-2022
    if: ${{ inputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag }}

      - name: Get Build Version from git tag
        id: get_build_version
        run: |
        echo "target version is ${{ inputs.tag }}"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'
          architecture: 'x64'
          allow-prereleases: true

      - name: Install GKFlasher Requirements
        run: |
          pip install -r requirements.txt
          
      - name: Embed version into package
        run: |
          echo "__version__ = '${{ inputs.tag }}'" > _version.py
      - name: Install Build Environment Prerequisites
        run: |
          pip install pyinstaller==6.12.0
          pip install cryptography==43.0.3
          pip install pillow==11.0.0
          
      - name: Build EXE Package
        run: |
          python -m PyInstaller .github/workflows/gui.spec
#  for debug purposes, upload the build artifact as a zip.         
      - uses: actions/upload-artifact@v4
        with:
          ##name: Upload PyInstaller "Output" Directory
          path: dist/*

      - name: Install WiX
        run: dotnet tool install --global wix --version 5.0.2

      - name: Build MSI Package
        run: |
           candle .github/workflows/dialog.wxs .github/workflows/ui.wxs .github/workflows/product.wxs -dversion="${{ inputs.tag }}"
           light -ext WixUIExtension -ext WixUtilExtension -sacl -spdb  -out ./GKFlasher-${{ inputs.tag }}-amd64.msi ./dialog.wixobj ./ui.wixobj ./product.wixobj

      - name: Upload MSI to Releases
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ inputs.tag }}
          prerelease: false
          title: ${{ inputs.tag }}
          files: |
            GKFlasher-${{ inputs.tag }}-amd64.msi
